"""Compatibility exports for the provider-neutral secret contracts."""

from gigaloom.secrets import (
    MAX_SECRET_CACHE_TTL_SECONDS,
    SECRET_REFERENCE_SCHEMA_VERSION,
    CompositeSecretResolver,
    EnvironmentSecretResolver,
    KeychainSecretReader,
    KeychainSecretResolver,
    MemorySecretResolver,
    ResolvedSecret,
    SecretReference,
    SecretReferenceKind,
    SecretResolutionError,
    SecretResolutionErrorCode,
    SecretResolutionEvidence,
    SecretResolutionService,
    SecretResolutionState,
    SecretResolver,
    SecretSourceProvenance,
    secret_reference_from_dict,
    secret_reference_to_dict,
    secret_resolution_evidence_to_dict,
)

__all__ = [
    "MAX_SECRET_CACHE_TTL_SECONDS",
    "SECRET_REFERENCE_SCHEMA_VERSION",
    "CompositeSecretResolver",
    "EnvironmentSecretResolver",
    "KeychainSecretReader",
    "KeychainSecretResolver",
    "MemorySecretResolver",
    "ResolvedSecret",
    "SecretReference",
    "SecretReferenceKind",
    "SecretResolutionError",
    "SecretResolutionErrorCode",
    "SecretResolutionEvidence",
    "SecretResolutionService",
    "SecretResolutionState",
    "SecretResolver",
    "SecretSourceProvenance",
    "secret_reference_from_dict",
    "secret_reference_to_dict",
    "secret_resolution_evidence_to_dict",
]
