"""Compatibility facade for typed TUI contracts and transport adapters."""

from gigaloom.tui.clients.http import AttachedWorkbenchClient
from gigaloom.tui.clients.in_process import InProcessWorkbenchClient
from gigaloom.tui.clients.protocol import WorkbenchClient
from gigaloom.tui.contracts import (
    MAX_PROJECTS,
    MAX_SESSIONS,
    MAX_RESPONSE_BYTES,
    MAX_DISPLAY_CHARS,
    MAX_TIMELINE_EVENTS,
    MAX_TIMELINE_CHARS,
    MAX_FILE_CANDIDATES,
    MAX_FILE_PREVIEW_CHARS,
    MAX_DIFF_PREVIEW_CHARS,
    MAX_NATIVE_SCROLLBACK_CHARS,
    MAX_NATIVE_INPUT_CHARS,
    HTTP_TIMEOUT_SECONDS,
    RUN_START_TIMEOUT_SECONDS,
    RUN_STREAM_RESNAPSHOT_SECONDS,
    MAX_SSE_LINE_BYTES,
    WorkbenchClientError,
    ProjectSummary,
    SessionSummary,
    SessionActionBinding,
    SessionPreview,
    SessionExport,
    HarnessSummary,
    ReadinessSummary,
    IntegrationSummary,
    EnvironmentSummary,
    EnvironmentCommitPreviewSummary,
    EnvironmentCommitApplySummary,
    EnvironmentPushPreviewSummary,
    EnvironmentPushApplySummary,
    EnvironmentPullRequestPreviewSummary,
    EnvironmentPullRequestApplySummary,
    NavigationSnapshot,
    RunActionBinding,
    TimelineEvent,
    ApprovalSummary,
    RunSnapshot,
    FileCandidate,
    AttachmentSummary,
    ArtifactSummary,
    RunInspection,
    HandoffPreview,
    NativeTerminalSnapshot,
)
from gigaloom.tui.projections.native import neutralize_native_terminal_output
from gigaloom.tui.projections.navigation import session_action_binding

__all__ = [
    "AttachedWorkbenchClient",
    "InProcessWorkbenchClient",
    "WorkbenchClient",
    "neutralize_native_terminal_output",
    "session_action_binding",
    "MAX_PROJECTS",
    "MAX_SESSIONS",
    "MAX_RESPONSE_BYTES",
    "MAX_DISPLAY_CHARS",
    "MAX_TIMELINE_EVENTS",
    "MAX_TIMELINE_CHARS",
    "MAX_FILE_CANDIDATES",
    "MAX_FILE_PREVIEW_CHARS",
    "MAX_DIFF_PREVIEW_CHARS",
    "MAX_NATIVE_SCROLLBACK_CHARS",
    "MAX_NATIVE_INPUT_CHARS",
    "HTTP_TIMEOUT_SECONDS",
    "RUN_START_TIMEOUT_SECONDS",
    "RUN_STREAM_RESNAPSHOT_SECONDS",
    "MAX_SSE_LINE_BYTES",
    "WorkbenchClientError",
    "ProjectSummary",
    "SessionSummary",
    "SessionActionBinding",
    "SessionPreview",
    "SessionExport",
    "HarnessSummary",
    "ReadinessSummary",
    "IntegrationSummary",
    "EnvironmentSummary",
    "EnvironmentCommitPreviewSummary",
    "EnvironmentCommitApplySummary",
    "EnvironmentPushPreviewSummary",
    "EnvironmentPushApplySummary",
    "EnvironmentPullRequestPreviewSummary",
    "EnvironmentPullRequestApplySummary",
    "NavigationSnapshot",
    "RunActionBinding",
    "TimelineEvent",
    "ApprovalSummary",
    "RunSnapshot",
    "FileCandidate",
    "AttachmentSummary",
    "ArtifactSummary",
    "RunInspection",
    "HandoffPreview",
    "NativeTerminalSnapshot",
]

# Preserve the historical pickle/import identity while the facade is supported.
for _public_type in (
    WorkbenchClientError,
    ProjectSummary,
    SessionSummary,
    SessionActionBinding,
    SessionPreview,
    SessionExport,
    HarnessSummary,
    ReadinessSummary,
    IntegrationSummary,
    EnvironmentSummary,
    EnvironmentCommitPreviewSummary,
    EnvironmentCommitApplySummary,
    EnvironmentPushPreviewSummary,
    EnvironmentPushApplySummary,
    EnvironmentPullRequestPreviewSummary,
    EnvironmentPullRequestApplySummary,
    NavigationSnapshot,
    RunActionBinding,
    TimelineEvent,
    ApprovalSummary,
    RunSnapshot,
    FileCandidate,
    AttachmentSummary,
    ArtifactSummary,
    RunInspection,
    HandoffPreview,
    NativeTerminalSnapshot,
):
    _public_type.__module__ = __name__

del _public_type
