"""Stable, product-neutral public contracts."""

from gigaloom.contracts.config import HarnessConfig
from gigaloom.contracts.context import (
    CONTEXT_MANIFEST_FORMAT,
    CONTEXT_MANIFEST_SCHEMA_VERSION,
    CompactionBoundary,
    ContextEntry,
    ContextEntryKind,
    ContextManifest,
    ContextOmission,
    ContextOverride,
    InclusionReason,
    OmissionReason,
    ProviderManagedUnknown,
    TokenEstimate,
    TokenEstimateConfidence,
    TokenEstimateMethod,
    build_context_manifest,
    context_manifest_schema,
)
from gigaloom.contracts.context_cache import (
    ContextManifestCache,
    StaleContextManifestError,
)
from gigaloom.contracts.context_serialization import context_manifest_from_dict
from gigaloom.contracts.events import (
    HarnessEvent,
    HarnessEventType,
    emit_event,
)
from gigaloom.contracts.execution import (
    ExecutionTransport,
    HarnessInvocationMode,
)
from gigaloom.contracts.harness import (
    AdapterCapabilitySupport,
    AdapterSupportLevel,
    AttachmentTransportSupport,
    Availability,
    AvailabilityStatus,
    HarnessCapability,
    HarnessChatMessage,
    HarnessContext,
    HarnessRequest,
    HarnessResult,
    HarnessSpec,
    HeadlessContinuationStrategy,
    parse_capability,
)
from gigaloom.contracts.providers import (
    GIGACHAT_BUILTIN_TOOLS,
    GigaChatApiMode,
    GigaChatBuiltinTool,
    parse_api_mode,
    parse_builtin_tools,
)
from gigaloom.contracts.serialization import (
    availability_to_dict,
    event_to_dict,
    result_to_dict,
    spec_capability_values,
    spec_to_dict,
)

__all__ = [
    "AdapterCapabilitySupport",
    "AdapterSupportLevel",
    "AttachmentTransportSupport",
    "Availability",
    "AvailabilityStatus",
    "CONTEXT_MANIFEST_FORMAT",
    "CONTEXT_MANIFEST_SCHEMA_VERSION",
    "CompactionBoundary",
    "ContextEntry",
    "ContextEntryKind",
    "ContextManifest",
    "ContextManifestCache",
    "ContextOmission",
    "ContextOverride",
    "ExecutionTransport",
    "GIGACHAT_BUILTIN_TOOLS",
    "GigaChatApiMode",
    "GigaChatBuiltinTool",
    "HarnessCapability",
    "HarnessChatMessage",
    "HarnessConfig",
    "HarnessContext",
    "HarnessEvent",
    "HarnessEventType",
    "HarnessInvocationMode",
    "HarnessRequest",
    "HarnessResult",
    "HarnessSpec",
    "HeadlessContinuationStrategy",
    "InclusionReason",
    "OmissionReason",
    "ProviderManagedUnknown",
    "StaleContextManifestError",
    "TokenEstimate",
    "TokenEstimateConfidence",
    "TokenEstimateMethod",
    "availability_to_dict",
    "build_context_manifest",
    "context_manifest_from_dict",
    "context_manifest_schema",
    "emit_event",
    "event_to_dict",
    "parse_api_mode",
    "parse_builtin_tools",
    "parse_capability",
    "result_to_dict",
    "spec_capability_values",
    "spec_to_dict",
]
