"""Public Visual QA gate API."""

from gigaloom.automation.evaluations.visual.api import (
    BrowserCaptureRequest,
    BrowserCaptureResult,
    BrowserConsoleLevel,
    BrowserConsoleObservation,
    BrowserDomObservation,
    BrowserFingerprint,
    BrowserRequestObservation,
    CollectedVisualEvidence,
    DomAssertionKind,
    DomAssertionSpec,
    FilesystemVisualArtifactStore,
    FilesystemVisualGateStore,
    ScreenshotRedactionSpec,
    VisualBrowserAdmission,
    VisualBrowserPort,
    VisualArtifactStorePort,
    VisualGateStorePort,
    VisualProcessNetworkGrant,
    VisualRedactionPolicy,
    admit_visual_target,
    collect_browser_evidence,
    project_visual_gate_evidence,
    run_visual_gate,
    validate_navigation_url,
)

__all__ = [
    "BrowserCaptureRequest",
    "BrowserCaptureResult",
    "BrowserConsoleLevel",
    "BrowserConsoleObservation",
    "BrowserDomObservation",
    "BrowserFingerprint",
    "BrowserRequestObservation",
    "CollectedVisualEvidence",
    "DomAssertionKind",
    "DomAssertionSpec",
    "FilesystemVisualArtifactStore",
    "FilesystemVisualGateStore",
    "ScreenshotRedactionSpec",
    "VisualBrowserAdmission",
    "VisualBrowserPort",
    "VisualArtifactStorePort",
    "VisualGateStorePort",
    "VisualProcessNetworkGrant",
    "VisualRedactionPolicy",
    "admit_visual_target",
    "collect_browser_evidence",
    "project_visual_gate_evidence",
    "run_visual_gate",
    "validate_navigation_url",
]
