from pathlib import Path

from gigaloom.capability_matrix import (
    AGENT_SURFACE_MATRIX_SOURCE,
    CAPABILITY_MATRIX_SOURCE,
    build_adapter_capability_matrix,
    build_agent_surface_capability_matrix,
    render_adapter_capability_matrix_markdown,
    render_agent_surface_capability_matrix_markdown,
)
from gigaloom.registry import HarnessRegistry
from gigaloom.types import spec_to_dict

REPOSITORY_ROOT = Path(__file__).parents[2]


def test_capability_matrix_is_generated_from_builtin_runtime_contracts():
    registry = HarnessRegistry.with_builtins()

    matrix = build_adapter_capability_matrix(registry)

    assert matrix["schema_version"] == 1
    assert matrix["generated_from"] == CAPABILITY_MATRIX_SOURCE
    assert matrix["built_in_only"] is True
    assert [item["id"] for item in matrix["adapters"]] == [
        "claude-code",
        "codex-cli",
        "gemini-cli",
    ]

    cells = {item["id"]: item["support"] for item in matrix["capabilities"]}
    adapter_ids = {item["id"] for item in matrix["adapters"]}
    for harness in registry.list():
        spec = spec_to_dict(harness.spec())
        claims = spec["adapter_capabilities"]
        if not claims:
            assert spec["id"] not in adapter_ids
            continue
        assert spec["protocol_capability_scope"] == "harness_surface"
        generated_claims = {
            capability_id: cells[capability_id][spec["id"]] for capability_id in claims
        }
        assert generated_claims == claims


def test_capability_matrix_markdown_contains_statuses_and_evidence():
    matrix = build_adapter_capability_matrix(HarnessRegistry.with_builtins())

    rendered = render_adapter_capability_matrix_markdown(matrix)

    assert rendered.startswith("# Harness adapter capability matrix\n")
    assert "Generated from `HarnessSpec.adapter_capabilities`" in rendered
    assert (
        "| `headless_continuity` | unsupported | supported | unsupported |" in rendered
    )
    assert "## Contract evidence" in rendered
    assert "Uses a supervised Codex app-server thread" in rendered


def test_agent_surface_matrix_is_generated_from_builtin_contracts():
    matrix = build_agent_surface_capability_matrix(HarnessRegistry.with_builtins())

    assert matrix["schema_version"] == 1
    assert matrix["generated_from"] == AGENT_SURFACE_MATRIX_SOURCE
    assert [item["id"] for item in matrix["surfaces"]] == [
        "direct-chat",
        "codex-cli",
        "claude-code",
        "gemini-cli",
    ]

    cells = {item["id"]: item["support"] for item in matrix["capabilities"]}
    assert cells["execution_route"]["direct-chat"]["status"] == "supported"
    assert cells["managed_mcp"]["direct-chat"]["status"] == "unsupported"
    assert cells["managed_mcp"]["codex-cli"]["status"] == "supported"
    assert cells["session_continuity"]["codex-cli"]["status"] == "partial"
    assert cells["hidden_reasoning_transfer"]["gemini-cli"]["status"] == ("unsupported")


def test_agent_surface_matrix_markdown_matches_published_guide():
    matrix = build_agent_surface_capability_matrix(HarnessRegistry.with_builtins())
    rendered = render_agent_surface_capability_matrix_markdown(matrix)

    assert rendered.startswith("# GigaLoom agent surface capability matrix\n")
    assert "Generated by `giga harness capabilities --agents`" in rendered
    assert (
        "| `managed_mcp` | unsupported | supported | supported | supported |"
        in rendered
    )
    assert (REPOSITORY_ROOT / "docs" / "agent-capability-matrix.md").read_text(
        encoding="utf-8"
    ) == rendered
