"""Public facade for cross-context native operator primitives."""

from __future__ import annotations

from importlib import import_module
from typing import Any

from gigaloom.native.launch import (
    AgentResolutionKind,
    AgentResolutionReason,
    AgentResolutionResult,
    BridgeRouteV1,
    DEFAULT_GATEWAY_DISCOVERY_TTL_SECONDS,
    DEFAULT_GATEWAY_STARTUP_POLL_SECONDS,
    DEFAULT_GATEWAY_STARTUP_TIMEOUT_SECONDS,
    GATEWAY_LAUNCH_SCHEMA_VERSION,
    GatewayMode,
    GatewayArtifactEvidenceV1,
    GatewayAgentInjectionV1,
    GatewayDiscoveryError,
    GatewayDiscoveryReason,
    GatewayDiscoveryResult,
    GatewayDiscoveryStatus,
    GatewayMachineTransport,
    GatewayInjectionReason,
    GatewayInjectionStatus,
    GatewayPreflightReceiptV1,
    GatewayPreflightStatus,
    GatewayProcessLeaseOwner,
    GatewayProfileV1,
    GatewayRouteCatalogV1,
    GatewayRouteDiscovery,
    GatewaySidecarReason,
    GatewaySidecarStatus,
    GatewayStartupReadinessProbe,
    GatewaySupportStatus,
    LaunchOverlayV1,
    ManagedGatewayLeaseV1,
    ManagedGatewaySidecarService,
    NativeAgentLaunchSpec,
    NativeIntentMatcher,
    NativeIntentMatcherKind,
    NativeInvocation,
    NativeLaunchMode,
    NativeLaunchPlan,
    NativeLaunchReason,
    TerminalContext,
    UrlLibGatewayMachineTransport,
    UrlLibGatewayStartupReadinessProbe,
    bridge_route_from_dict,
    bridge_route_to_dict,
    build_gateway_agent_injection,
    gateway_contract_digest,
    gateway_preflight_receipt_from_dict,
    gateway_preflight_receipt_to_dict,
    gateway_profile_from_dict,
    gateway_profile_to_dict,
    launch_overlay_from_dict,
    launch_overlay_to_dict,
    plan_native_launch,
)

CodexStdioJsonRpcClient: Any

__all__ = [
    "AgentResolutionKind",
    "AgentResolutionReason",
    "AgentResolutionResult",
    "BridgeRouteV1",
    "CodexStdioJsonRpcClient",
    "DEFAULT_GATEWAY_DISCOVERY_TTL_SECONDS",
    "DEFAULT_GATEWAY_STARTUP_POLL_SECONDS",
    "DEFAULT_GATEWAY_STARTUP_TIMEOUT_SECONDS",
    "GATEWAY_LAUNCH_SCHEMA_VERSION",
    "GatewayMode",
    "GatewayArtifactEvidenceV1",
    "GatewayAgentInjectionV1",
    "GatewayDiscoveryError",
    "GatewayDiscoveryReason",
    "GatewayDiscoveryResult",
    "GatewayDiscoveryStatus",
    "GatewayMachineTransport",
    "GatewayInjectionReason",
    "GatewayInjectionStatus",
    "GatewayPreflightReceiptV1",
    "GatewayPreflightStatus",
    "GatewayProcessLeaseOwner",
    "GatewayProfileV1",
    "GatewayRouteCatalogV1",
    "GatewayRouteDiscovery",
    "GatewaySidecarReason",
    "GatewaySidecarStatus",
    "GatewayStartupReadinessProbe",
    "GatewaySupportStatus",
    "LaunchOverlayV1",
    "ManagedGatewayLeaseV1",
    "ManagedGatewaySidecarService",
    "NativeAgentLaunchSpec",
    "NativeIntentMatcher",
    "NativeIntentMatcherKind",
    "NativeInvocation",
    "NativeLaunchMode",
    "NativeLaunchPlan",
    "NativeLaunchReason",
    "TerminalContext",
    "UrlLibGatewayMachineTransport",
    "UrlLibGatewayStartupReadinessProbe",
    "bridge_route_from_dict",
    "bridge_route_to_dict",
    "build_gateway_agent_injection",
    "gateway_contract_digest",
    "gateway_preflight_receipt_from_dict",
    "gateway_preflight_receipt_to_dict",
    "gateway_profile_from_dict",
    "gateway_profile_to_dict",
    "launch_overlay_from_dict",
    "launch_overlay_to_dict",
    "plan_native_launch",
]


def __getattr__(name: str) -> Any:
    """Resolve compatibility-stable operator clients lazily."""
    if name != "CodexStdioJsonRpcClient":
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(
        import_module("gigaloom.native.codex_operator.protocol"),
        name,
    )
    globals()[name] = value
    return value
