"""Bounded local storage for files generated by upstream built-in tools."""

from __future__ import annotations

import base64
import binascii
from hashlib import sha256
from pathlib import Path
import re
from typing import Any, Mapping
from urllib.parse import quote

MAX_GENERATED_FILE_BYTES = 25 * 1024 * 1024
GENERATED_FILES_DIR = "generated-files"
_SAFE_SEGMENT = re.compile(r"^[a-f0-9]{64}$")
_GENERATED_FILE_EXTENSIONS = {
    "application/json": ".json",
    "application/pdf": ".pdf",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation": ".pptx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": ".xlsx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": ".docx",
    "application/zip": ".zip",
    "image/avif": ".avif",
    "image/bmp": ".bmp",
    "image/gif": ".gif",
    "image/jpeg": ".jpg",
    "image/png": ".png",
    "image/webp": ".webp",
    "text/csv": ".csv",
    "text/html": ".html",
    "text/markdown": ".md",
    "text/plain": ".txt",
}
_IMAGE_MIME_TYPES = frozenset(
    mime_type
    for mime_type in _GENERATED_FILE_EXTENSIONS
    if mime_type.startswith("image/")
)
_GENERATED_TARGETS = frozenset({"doc", "file", "image"})


class GeneratedFileError(ValueError):
    """Raised when generated file metadata or content is unsafe."""


def persist_generated_image(
    data_dir: str | Path,
    *,
    run_id: str,
    file_id: str,
    mime_type: str,
    content_base64: str,
) -> dict[str, Any]:
    """Decode and persist one generated image under the Harness data directory."""
    if mime_type.lower() not in _IMAGE_MIME_TYPES:
        raise GeneratedFileError("unsupported generated image type")
    return persist_generated_file(
        data_dir,
        run_id=run_id,
        file_id=file_id,
        mime_type=mime_type,
        target="image",
        content_base64=content_base64,
    )


def persist_generated_file(
    data_dir: str | Path,
    *,
    run_id: str,
    file_id: str,
    mime_type: str,
    target: str,
    content_base64: str,
) -> dict[str, Any]:
    """Decode and persist one allowlisted generated file under managed storage."""
    normalized_mime_type = mime_type.lower()
    extension = _GENERATED_FILE_EXTENSIONS.get(normalized_mime_type)
    if extension is None:
        raise GeneratedFileError("unsupported generated file type")
    normalized_target = target.lower()
    if normalized_target not in _GENERATED_TARGETS:
        raise GeneratedFileError("unsupported generated file target")
    if normalized_mime_type in _IMAGE_MIME_TYPES:
        normalized_target = "image"
    try:
        content = base64.b64decode(content_base64, validate=True)
    except (binascii.Error, ValueError) as exc:
        raise GeneratedFileError("generated file content is not valid base64") from exc
    if not content or len(content) > MAX_GENERATED_FILE_BYTES:
        raise GeneratedFileError("generated file size is outside the allowed range")

    run_key = _digest(run_id)
    file_key = _digest(file_id)
    filename = f"{file_key}{extension}"
    directory = generated_files_root(data_dir) / run_key
    directory.mkdir(parents=True, exist_ok=True)
    target = directory / filename
    temporary = target.with_suffix(f"{target.suffix}.tmp")
    temporary.write_bytes(content)
    temporary.replace(target)
    display_filename = f"generated-{file_key[:12]}{extension}"
    file_url = f"/api/files/generated/{run_key}/{filename}"
    result = {
        "id": file_id,
        "file_id": file_id,
        "filename": display_filename,
        "mime_type": normalized_mime_type,
        "target": normalized_target,
        "size_bytes": len(content),
        "download_url": f"{file_url}?download={quote(display_filename)}",
    }
    if normalized_target == "image":
        result["preview_url"] = file_url
    return result


def generated_file_path(
    data_dir: str | Path,
    run_key: str,
    filename: str,
) -> Path:
    """Resolve a hashed generated-file URL without allowing path traversal."""
    suffix = Path(filename).suffix.lower()
    file_key = Path(filename).stem
    if not _SAFE_SEGMENT.fullmatch(run_key) or not _SAFE_SEGMENT.fullmatch(file_key):
        raise GeneratedFileError("invalid generated file path")
    if suffix not in set(_GENERATED_FILE_EXTENSIONS.values()):
        raise GeneratedFileError("unsupported generated file extension")
    root = generated_files_root(data_dir)
    resolved = (root / run_key / filename).resolve()
    if not resolved.is_relative_to(root):
        raise GeneratedFileError("generated file escapes its storage root")
    return resolved


def generated_files_root(data_dir: str | Path) -> Path:
    """Return the resolved generated-file storage root."""
    return Path(data_dir).expanduser().resolve() / GENERATED_FILES_DIR


def generated_image_metadata(value: Mapping[str, Any]) -> tuple[str, str] | None:
    """Return ``(file_id, mime_type)`` for a supported generated image."""
    file_id = value.get("id")
    mime_type = value.get("mime") or value.get("mime_type")
    target = value.get("target")
    if not isinstance(file_id, str) or not file_id:
        return None
    if not isinstance(mime_type, str) or mime_type.lower() not in _IMAGE_MIME_TYPES:
        return None
    if target not in {None, "image"}:
        return None
    return file_id, mime_type.lower()


def generated_file_metadata(value: Mapping[str, Any]) -> tuple[str, str, str] | None:
    """Return allowlisted ``(file_id, mime_type, target)`` generated metadata."""
    file_id = value.get("id")
    mime_type = value.get("mime") or value.get("mime_type")
    target = value.get("target")
    if not isinstance(file_id, str) or not file_id:
        return None
    if not isinstance(mime_type, str):
        return None
    normalized_mime_type = mime_type.lower()
    if normalized_mime_type not in _GENERATED_FILE_EXTENSIONS:
        return None
    if target is None:
        normalized_target = (
            "image" if normalized_mime_type in _IMAGE_MIME_TYPES else "file"
        )
    elif isinstance(target, str) and target.lower() in _GENERATED_TARGETS:
        normalized_target = target.lower()
    else:
        return None
    if normalized_mime_type in _IMAGE_MIME_TYPES:
        normalized_target = "image"
    return file_id, normalized_mime_type, normalized_target


def _digest(value: str) -> str:
    return sha256(value.encode("utf-8")).hexdigest()
