"""Generic local-stdio Agent Client Protocol gateway."""

from gigaloom.harnesses.acp.api import (
    ACP_PROTOCOL_VERSION,
    AcpCapabilitySnapshotV1,
    AcpClient,
    AcpClientInfo,
    AcpLimits,
    AcpProcessSpec,
    AcpPromptHandle,
    AcpRouteIdentity,
    AcpSessionBindingV1,
    AcpPermissionContextV1,
    AcpPermissionRequestV1,
    begin_prompt,
    close_session,
    create_acp_client,
    delete_session,
    list_sessions,
    load_session,
    new_session,
    next_permission,
    pin_acp_process,
    respond_permission,
    resume_session,
    set_session_config,
)

__all__ = [
    "ACP_PROTOCOL_VERSION",
    "AcpCapabilitySnapshotV1",
    "AcpClient",
    "AcpClientInfo",
    "AcpLimits",
    "AcpProcessSpec",
    "AcpPromptHandle",
    "AcpRouteIdentity",
    "AcpSessionBindingV1",
    "AcpPermissionContextV1",
    "AcpPermissionRequestV1",
    "begin_prompt",
    "close_session",
    "create_acp_client",
    "delete_session",
    "list_sessions",
    "load_session",
    "new_session",
    "next_permission",
    "pin_acp_process",
    "respond_permission",
    "resume_session",
    "set_session_config",
]
