"""Deterministic Integration SDK preview package scaffolding."""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path

from gpt2giga_harness.integration_packages import (
    InstallationScope,
    IntegrationComponent,
    IntegrationComponentType,
    IntegrationPackage,
    IntegrationSourceType,
    IntegrationTrustEvidence,
    IntegrationTrustKind,
    IntegrationTrustStatus,
    IntegrationUpdatePolicy,
    integration_package_to_dict,
)


@dataclass(frozen=True)
class IntegrationScaffoldResult:
    """Files created for one immutable sample integration package."""

    root: Path
    package_id: str
    files: tuple[Path, ...]


def scaffold_integration_package(
    package_id: str,
    destination: str | Path,
) -> IntegrationScaffoldResult:
    """Create a portable Skill package scaffold and refuse overwrites."""
    root = Path(destination).resolve()
    if root.exists():
        raise FileExistsError(f"scaffold destination already exists: {root}")
    skill = _render_skill(package_id)
    digest = "sha256:" + hashlib.sha256(skill.encode("utf-8")).hexdigest()
    package = IntegrationPackage(
        id=package_id,
        version="0.1.0",
        publisher="example.internal",
        license="MIT",
        source_type=IntegrationSourceType.LOCAL,
        source="payload/SKILL.md",
        immutable_ref=digest,
        checksum=digest,
        components=(
            IntegrationComponent(
                id="portable-skill",
                type=IntegrationComponentType.SKILL,
                portable=True,
            ),
        ),
        requirements=(),
        overlays=(),
        compatibility=(),
        scopes=(InstallationScope.MANAGED_HOME, InstallationScope.PROJECT),
        update_policy=IntegrationUpdatePolicy.PINNED,
        verification_steps=("skill.parse",),
        rollback_steps=("installer.restore",),
        trust_evidence=(
            IntegrationTrustEvidence(
                id="sample-source",
                kind=IntegrationTrustKind.SOURCE,
                status=IntegrationTrustStatus.UNVERIFIED,
                authority="sdk-scaffold",
                revision="v1",
            ),
        ),
    )
    rendered = {
        root / "README.md": _render_readme(package_id),
        root / "integration-package.json": (
            json.dumps(integration_package_to_dict(package), indent=2, sort_keys=True)
            + "\n"
        ),
        root / "payload" / "SKILL.md": skill,
    }
    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return IntegrationScaffoldResult(
        root=root,
        package_id=package.id,
        files=tuple(sorted(rendered)),
    )


def _render_readme(package_id: str) -> str:
    return f"""# {package_id}

Generated internal Integration SDK preview package.

The manifest is immutable and content-free. Its trust evidence is deliberately
unverified: successful conformance never grants installation authority.

```bash
giga integration conformance integration-package.json --json
```
"""


def _render_skill(package_id: str) -> str:
    return f"""---
name: {package_id}
description: Example portable Skill generated by the Integration SDK preview.
---

# {package_id}

Replace this sample with reviewed, provider-neutral instructions.
"""


__all__ = ["IntegrationScaffoldResult", "scaffold_integration_package"]
