#!/usr/bin/env python3
"""Prepare and verify all tracked GigaLoom release identity projections."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import difflib
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import stat
import tempfile
import tomllib
from typing import Any, Mapping, Sequence


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
VERSION_PATH = Path("release/version.toml")
PRODUCT_INVENTORY_PATH = Path(
    "src/gigaloom/evidence/product_inventory/v1/inventory.json"
)
RELEASE_BUMP_SCHEMA = "gigaloom.release-bump.v1"
SEMVER_PATTERN = r"\d+\.\d+\.\d+(?:-(?:alpha|beta|rc)\.[1-9]\d*)?"
PEP440_PATTERN = r"\d+\.\d+\.\d+(?:(?:a|b|rc)[1-9]\d*)?"
SEMVER_RE = re.compile(
    r"(?P<base>\d+\.\d+\.\d+)"
    r"(?:-(?P<stage>alpha|beta|rc)\.(?P<number>[1-9]\d*))?"
)
GENERATED_DOC_MARKER = (
    "<!-- Release-version snippets in this file are generated by "
    "scripts/release.py. -->"
)
GENERATED_MDX_MARKER = (
    "{/* Release-version snippets in this file are generated by scripts/release.py. */}"
)
GENERATED_SCRIPT_MARKER = (
    "// Release-version expectations in this file are generated by scripts/release.py."
)
DOCUMENT_PROJECTIONS = (
    Path("README.md"),
    Path("docs/index.md"),
    Path("docs/installation.md"),
    Path("docs/release.md"),
    Path("docs/gateway-integration.md"),
    Path("docs/harness.md"),
    Path("web/README.md"),
    Path("docs-site/i18n/ru/docusaurus-plugin-content-docs/current/index.md"),
    Path("docs-site/i18n/ru/docusaurus-plugin-content-docs/current/installation.md"),
    Path("docs-site/i18n/ru/docusaurus-plugin-content-docs/current/release.md"),
    Path(
        "docs-site/i18n/ru/docusaurus-plugin-content-docs/current/"
        "gateway-integration.md"
    ),
    Path("docs-site/i18n/ru/docusaurus-plugin-content-docs/current/harness.md"),
)
CHANGELOG_PROJECTIONS = (Path("CHANGELOG.md"), Path("CHANGELOG_en.md"))


class ReleasePreparationError(RuntimeError):
    """Raised when release identity cannot be prepared safely."""


@dataclass(frozen=True)
class ReleaseIdentity:
    """Canonical release identity and ecosystem projections."""

    version: str
    python_version: str
    git_tag: str


@dataclass(frozen=True)
class ArtifactEntry:
    """One role-named file copied into a release candidate."""

    role: str
    source: Path
    target: Path


def release_identity(version: str) -> ReleaseIdentity:
    """Validate a supported SemVer value and derive its projections."""
    match = SEMVER_RE.fullmatch(version)
    if match is None:
        raise ReleasePreparationError(f"unsupported release version: {version!r}")
    stage = match.group("stage")
    number = match.group("number")
    python_version = match.group("base")
    if stage is not None:
        python_stage = {"alpha": "a", "beta": "b", "rc": "rc"}[stage]
        python_version += f"{python_stage}{number}"
    return ReleaseIdentity(version, python_version, f"v{version}")


def read_canonical_identity(root: Path) -> ReleaseIdentity:
    """Read the only hand-edited release identity file."""
    path = root / VERSION_PATH
    try:
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ReleasePreparationError(
            f"cannot read canonical release file: {path}"
        ) from exc
    if set(payload) != {"version"} or not isinstance(payload["version"], str):
        raise ReleasePreparationError("release/version.toml must contain only version")
    return release_identity(payload["version"])


def _read_text(root: Path, relative: Path) -> str:
    path = root / relative
    try:
        if path.is_symlink() or not path.is_file():
            raise OSError("not a regular file")
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise ReleasePreparationError(
            f"cannot read release projection: {relative}"
        ) from exc


def _canonical_json(payload: Any) -> bytes:
    return f"{json.dumps(payload, indent=2, ensure_ascii=False)}\n".encode()


def _json_object(root: Path, relative: Path) -> dict[str, Any]:
    try:
        payload = json.loads(_read_text(root, relative))
    except json.JSONDecodeError as exc:
        raise ReleasePreparationError(f"malformed JSON projection: {relative}") from exc
    if not isinstance(payload, dict):
        raise ReleasePreparationError(f"JSON projection must be an object: {relative}")
    return payload


def _replace_once(text: str, pattern: str, replacement: str, *, label: str) -> str:
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise ReleasePreparationError(f"cannot locate exactly one {label}")
    return updated


def _project_document(text: str, identity: ReleaseIdentity, *, label: str) -> str:
    if not any(
        marker in text for marker in (GENERATED_DOC_MARKER, GENERATED_MDX_MARKER)
    ):
        raise ReleasePreparationError(f"{label} has no generated release marker")
    python_patterns = (
        rf"(?P<prefix>gigaloom(?:\[gpt2giga\])?==){PEP440_PATTERN}",
        rf"(?P<prefix>gigaloom-){PEP440_PATTERN}",
    )
    semver_patterns = (
        rf"(?P<prefix>@gigaloom/web@){SEMVER_PATTERN}",
        rf"(?P<prefix>\| Canonical release \| `){SEMVER_PATTERN}(?P<suffix>` \|)",
        rf"(?P<prefix>\| Git tag \| `v){SEMVER_PATTERN}(?P<suffix>` \|)",
        rf"(?P<prefix>The current `){SEMVER_PATTERN}(?P<suffix>` line)",
        rf"(?P<prefix>Линия `){SEMVER_PATTERN}(?P<suffix>`)",
    )
    lines: list[str] = []
    for line in text.splitlines(keepends=True):
        if "--prerelease allow" not in line:
            for pattern in python_patterns:
                line = re.sub(
                    pattern,
                    lambda match: f"{match.group('prefix')}{identity.python_version}",
                    line,
                )
        lines.append(line)
    text = "".join(lines)
    for pattern in semver_patterns:
        text = re.sub(
            pattern,
            lambda match: (
                f"{match.group('prefix')}{identity.version}"
                f"{match.groupdict().get('suffix') or ''}"
            ),
            text,
        )
    return text


def _project_candidate_report(text: str, identity: ReleaseIdentity) -> str:
    text = _replace_once(
        text,
        r"^# GigaLoom .* candidate report$",
        "# GigaLoom release candidate report",
        label="candidate report title",
    )
    start = "<!-- release.py:identity:start -->"
    end = "<!-- release.py:identity:end -->"
    if text.count(start) != 1 or text.count(end) != 1:
        raise ReleasePreparationError("candidate report identity markers are malformed")
    block = (
        f"{start}\nCandidate identity: `{identity.version}` / "
        f"`gigaloom=={identity.python_version}` /\n"
        f"`@gigaloom/web@{identity.version}`.\n{end}"
    )
    text = re.sub(
        rf"{re.escape(start)}.*?{re.escape(end)}",
        block,
        text,
        count=1,
        flags=re.DOTALL,
    )
    return _project_document(text, identity, label="release/candidate-report.md")


def _project_changelog(
    text: str,
    identity: ReleaseIdentity,
    previous: ReleaseIdentity,
    *,
    english: bool,
) -> str:
    heading = re.search(r"^## \[([^]]+)] - (.+)$", text, flags=re.MULTILINE)
    if heading is None:
        raise ReleasePreparationError("changelog has no release heading")
    if heading.group(1) == identity.version:
        return text
    section_title = "Added" if english else "Добавлено"
    pending = (
        f"## [{identity.version}] - Unreleased\n\n"
        f"### {section_title}\n\n"
        "- Release notes pending.\n\n"
        if english
        else f"## [{identity.version}] - Unreleased\n\n### {section_title}\n\n"
        "- Описание изменений будет добавлено перед публикацией.\n\n"
    )
    text = text[: heading.start()] + pending + text[heading.start() :]
    separator = "\n---\n"
    if separator not in text:
        raise ReleasePreparationError("changelog has no comparison-link separator")
    link = (
        f"[{identity.version}]: https://github.com/krakenalt/gigaloom/compare/"
        f"{previous.git_tag}...{identity.git_tag}\n"
    )
    link_offset = text.rfind(separator) + len(separator)
    return text[:link_offset] + "\n" + link + text[link_offset:]


def _artifact_manifest(identity: ReleaseIdentity) -> bytes:
    header = (
        "schema_version = 1\n"
        f'release = "{identity.version}"\n'
        f'python_version = "{identity.python_version}"\n'
        f'git_tag = "{identity.git_tag}"\n'
    )
    entries = (
        ("release_manifest", "release/release.json", "release.json"),
        ("artifact_manifest", "release/artifact-set.toml", "artifact-set.toml"),
        (
            "licenses",
            "src/gigaloom/ui/web/assets/_build/licenses.json",
            "licenses.json",
        ),
        (
            "web_provenance",
            "src/gigaloom/ui/web/assets/_build/provenance.json",
            "web-provenance.json",
        ),
        (
            "sbom",
            "src/gigaloom/ui/web/assets/_build/sbom.cdx.json",
            "sbom.cdx.json",
        ),
        (
            "external_evidence",
            "release/external-evidence.json",
            "external-evidence.json",
        ),
        ("candidate_report", "release/candidate-report.md", "candidate-report.md"),
        (
            "run_capsule_fixture",
            "tests/fixtures/run_capsules/read_only_run.json",
            "run-capsule-fixture.json",
        ),
    )
    body = "".join(
        f'\n[[artifacts]]\nrole = "{role}"\nsource = "{source}"\ntarget = "{target}"\n'
        for role, source, target in entries
    )
    return f"{header}{body}".encode()


def _product_inventory_digest(document: Mapping[str, Any]) -> str:
    payload = json.dumps(
        document,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode()
    return hashlib.sha256(payload).hexdigest()


def _project_product_inventory(
    root: Path,
    identity: ReleaseIdentity,
    previous: ReleaseIdentity,
) -> bytes:
    inventory = _json_object(root, PRODUCT_INVENTORY_PATH)
    claimed_digest = inventory.pop("content_sha256", None)
    if claimed_digest != _product_inventory_digest(inventory):
        raise ReleasePreparationError("product inventory digest is invalid")
    product = inventory.get("product")
    profiles = inventory.get("provider_compatibility_profiles")
    if not isinstance(product, dict) or not isinstance(profiles, list):
        raise ReleasePreparationError("product inventory release identity is malformed")
    current = product.get("version")
    if current not in {previous.python_version, identity.python_version}:
        raise ReleasePreparationError(
            "product inventory version differs from the canonical release"
        )
    product["version"] = identity.python_version
    for profile in profiles:
        if not isinstance(profile, dict):
            raise ReleasePreparationError(
                "product inventory compatibility profile is malformed"
            )
        if profile.get("adapter_version") not in {
            previous.python_version,
            identity.python_version,
        }:
            raise ReleasePreparationError(
                "product inventory adapter version differs from the canonical release"
            )
        profile["adapter_version"] = identity.python_version
    inventory["content_sha256"] = _product_inventory_digest(inventory)
    return f"{json.dumps(inventory, indent=2, ensure_ascii=False, sort_keys=True)}\n".encode()


def build_projections(root: Path, identity: ReleaseIdentity) -> dict[Path, bytes]:
    """Build every expected tracked projection without writing it."""
    previous = read_canonical_identity(root)
    projections: dict[Path, bytes] = {
        VERSION_PATH: f'version = "{identity.version}"\n'.encode(),
    }

    pyproject = _read_text(root, Path("pyproject.toml"))
    projections[Path("pyproject.toml")] = _replace_once(
        pyproject,
        r'(?ms)^(\[project]\n.*?^version = ")[^"]+("$)',
        rf"\g<1>{identity.python_version}\g<2>",
        label="Python project version",
    ).encode()
    uv_lock = _read_text(root, Path("uv.lock"))
    projections[Path("uv.lock")] = _replace_once(
        uv_lock,
        r'(?ms)^(\[\[package\]\]\nname = "gigaloom"\nversion = ")[^"]+("$)',
        rf"\g<1>{identity.python_version}\g<2>",
        label="locked Python project version",
    ).encode()

    package = _json_object(root, Path("web/package.json"))
    package["version"] = identity.version
    projections[Path("web/package.json")] = _canonical_json(package)
    lock = _json_object(root, Path("web/package-lock.json"))
    packages = lock.get("packages")
    if not isinstance(packages, dict) or not isinstance(packages.get(""), dict):
        raise ReleasePreparationError("web/package-lock.json has no root package")
    lock["version"] = identity.version
    packages[""]["version"] = identity.version
    projections[Path("web/package-lock.json")] = _canonical_json(lock)

    projections[Path("release/release.json")] = _canonical_json(
        {
            "release": identity.version,
            "git_tag": identity.git_tag,
            "python_distribution": "gigaloom",
            "python_version": identity.python_version,
            "npm_package": "@gigaloom/web",
            "npm_version": identity.version,
        }
    )
    external = _json_object(root, Path("release/external-evidence.json"))
    external["release"] = identity.version
    projections[Path("release/external-evidence.json")] = _canonical_json(external)
    projections[Path("release/artifact-set.toml")] = _artifact_manifest(identity)
    projections[PRODUCT_INVENTORY_PATH] = _project_product_inventory(
        root, identity, previous
    )

    report = _read_text(root, Path("release/candidate-report.md"))
    projections[Path("release/candidate-report.md")] = _project_candidate_report(
        report, identity
    ).encode()
    for relative in DOCUMENT_PROJECTIONS:
        projections[relative] = _project_document(
            _read_text(root, relative), identity, label=relative.as_posix()
        ).encode()

    script_contracts = (
        (
            Path("web/scripts/package-contract.mjs"),
            rf'(?m)^(const expectedVersion = "){SEMVER_PATTERN}(";$)',
            "npm package runtime contract version",
        ),
        (
            Path("web/scripts/package-contract.unit.mjs"),
            rf'(?m)^(  version: "){SEMVER_PATTERN}(",)$',
            "npm package unit contract version",
        ),
    )
    for relative, pattern, label in script_contracts:
        script_contract = _read_text(root, relative)
        if GENERATED_SCRIPT_MARKER not in script_contract:
            raise ReleasePreparationError(
                f"{relative.as_posix()} has no generated release marker"
            )
        projections[relative] = _replace_once(
            script_contract,
            pattern,
            rf"\g<1>{identity.version}\g<2>",
            label=label,
        ).encode()

    for relative in CHANGELOG_PROJECTIONS:
        projections[relative] = _project_changelog(
            _read_text(root, relative),
            identity,
            previous,
            english=relative.name == "CHANGELOG_en.md",
        ).encode()
    return projections


def _changed_projections(
    root: Path, expected: Mapping[Path, bytes]
) -> dict[Path, bytes]:
    changed: dict[Path, bytes] = {}
    for relative, content in expected.items():
        path = root / relative
        try:
            actual = path.read_bytes()
        except OSError as exc:
            raise ReleasePreparationError(
                f"cannot read release projection: {relative}"
            ) from exc
        if actual != content:
            changed[relative] = content
    return changed


def _temporary_file(path: Path, content: bytes, mode: int) -> Path:
    descriptor, name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary = Path(name)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.chmod(temporary, mode)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise
    return temporary


def apply_projections(root: Path, expected: Mapping[Path, bytes]) -> tuple[Path, ...]:
    """Replace and verify projections with rollback on an in-process failure."""
    changed = _changed_projections(root, expected)
    if not changed:
        return ()
    originals: dict[Path, tuple[bytes, int]] = {}
    staged: dict[Path, Path] = {}
    replaced: list[Path] = []
    try:
        for relative, content in changed.items():
            path = root / relative
            mode = stat.S_IMODE(path.stat().st_mode)
            originals[relative] = (path.read_bytes(), mode)
            staged[relative] = _temporary_file(path, content, mode)
        for relative in sorted(changed, key=lambda item: item == VERSION_PATH):
            staged[relative].replace(root / relative)
            replaced.append(relative)
        drift = _changed_projections(root, expected)
        if drift:
            raise ReleasePreparationError(
                "post-write release projection drift: "
                + ", ".join(path.as_posix() for path in drift)
            )
    except BaseException as exc:
        for relative in reversed(replaced):
            content, mode = originals[relative]
            rollback = _temporary_file(root / relative, content, mode)
            rollback.replace(root / relative)
        raise ReleasePreparationError("release preparation rolled back") from exc
    finally:
        for temporary in staged.values():
            temporary.unlink(missing_ok=True)
    return tuple(sorted(changed))


def verify_projections(root: Path) -> tuple[Path, ...]:
    """Return all release projections that differ from the canonical file."""
    identity = read_canonical_identity(root)
    return tuple(_changed_projections(root, build_projections(root, identity)))


def _safe_relative(value: Any, *, label: str) -> Path:
    if not isinstance(value, str) or not value or "\\" in value:
        raise ReleasePreparationError(f"invalid artifact {label}")
    pure = PurePosixPath(value)
    if pure.is_absolute() or ".." in pure.parts or pure.as_posix() != value:
        raise ReleasePreparationError(f"unsafe artifact {label}: {value!r}")
    return Path(*pure.parts)


def read_artifact_set(root: Path) -> tuple[ReleaseIdentity, tuple[ArtifactEntry, ...]]:
    """Decode the generated role-based artifact staging manifest."""
    path = root / "release/artifact-set.toml"
    try:
        payload = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ReleasePreparationError("artifact set is missing or malformed") from exc
    identity = read_canonical_identity(root)
    if (
        payload.get("schema_version") != 1
        or payload.get("release") != identity.version
        or payload.get("python_version") != identity.python_version
        or payload.get("git_tag") != identity.git_tag
    ):
        raise ReleasePreparationError(
            "artifact set identity differs from canonical release"
        )
    raw_entries = payload.get("artifacts")
    if not isinstance(raw_entries, list) or not raw_entries:
        raise ReleasePreparationError("artifact set has no artifacts")
    entries: list[ArtifactEntry] = []
    for raw in raw_entries:
        if not isinstance(raw, Mapping) or set(raw) != {"role", "source", "target"}:
            raise ReleasePreparationError("artifact entry does not match schema v1")
        role = raw["role"]
        if not isinstance(role, str) or re.fullmatch(r"[a-z][a-z0-9_]*", role) is None:
            raise ReleasePreparationError("artifact role is invalid")
        entries.append(
            ArtifactEntry(
                role,
                _safe_relative(raw["source"], label="source"),
                _safe_relative(raw["target"], label="target"),
            )
        )
    if len({entry.role for entry in entries}) != len(entries):
        raise ReleasePreparationError("artifact roles must be unique")
    if len({entry.target for entry in entries}) != len(entries):
        raise ReleasePreparationError("artifact targets must be unique")
    return identity, tuple(entries)


def stage_artifacts(root: Path, output: Path) -> tuple[Path, ...]:
    """Copy the generated artifact set into an existing candidate directory."""
    drift = verify_projections(root)
    if drift:
        raise ReleasePreparationError(
            "release projections drift: " + ", ".join(path.as_posix() for path in drift)
        )
    _, entries = read_artifact_set(root)
    if output.is_symlink():
        raise ReleasePreparationError("artifact output must not be a symlink")
    output = output.resolve()
    if output.exists() and not output.is_dir():
        raise ReleasePreparationError("artifact output must be a regular directory")
    output.mkdir(parents=True, exist_ok=True)
    copied: list[Path] = []
    for entry in entries:
        source = root / entry.source
        target = output / entry.target
        if source.is_symlink() or not source.is_file():
            raise ReleasePreparationError(
                f"artifact source is unavailable: {entry.source}"
            )
        target.parent.mkdir(parents=True, exist_ok=True)
        descriptor, name = tempfile.mkstemp(
            prefix=f".{target.name}.", dir=target.parent
        )
        os.close(descriptor)
        temporary = Path(name)
        try:
            shutil.copyfile(source, temporary)
            temporary.replace(target)
        finally:
            temporary.unlink(missing_ok=True)
        copied.append(entry.target)
    return tuple(copied)


def _render_diff(root: Path, expected: Mapping[Path, bytes]) -> str:
    chunks: list[str] = []
    for relative, content in expected.items():
        actual = (root / relative).read_text(encoding="utf-8").splitlines(keepends=True)
        target = content.decode().splitlines(keepends=True)
        chunks.extend(
            difflib.unified_diff(
                actual,
                target,
                fromfile=f"a/{relative.as_posix()}",
                tofile=f"b/{relative.as_posix()}",
            )
        )
    return "".join(chunks)


def _bump_receipt(identity: ReleaseIdentity, changed: Sequence[Path]) -> dict[str, Any]:
    return {
        "schema_version": RELEASE_BUMP_SCHEMA,
        "release": {
            "version": identity.version,
            "python_version": identity.python_version,
            "git_tag": identity.git_tag,
        },
        "changed": [path.as_posix() for path in changed],
        "verified": True,
        "next_steps": [
            {
                "id": "complete_changelogs",
                "kind": "edit",
                "paths": [path.as_posix() for path in CHANGELOG_PROJECTIONS],
            },
            {
                "id": "run_release_checks",
                "kind": "manual_gate",
                "documentation": "docs/release.md#maintainer-checklist",
            },
            {
                "id": "create_protected_tag",
                "kind": "external_gate",
                "git_tag": identity.git_tag,
            },
        ],
    }


def main(argv: Sequence[str] | None = None) -> int:
    """Run the release identity CLI."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=REPOSITORY_ROOT)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("show")
    prepare = commands.add_parser("prepare")
    prepare.add_argument("version")
    bump = commands.add_parser("bump")
    bump.add_argument("version")
    commands.add_parser("verify")
    difference = commands.add_parser("diff")
    difference.add_argument("version")
    stage = commands.add_parser("stage")
    stage.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    root = args.root.resolve()
    try:
        if args.command == "show":
            identity = read_canonical_identity(root)
            print(
                json.dumps(
                    {
                        "git_tag": identity.git_tag,
                        "python_version": identity.python_version,
                        "version": identity.version,
                    },
                    sort_keys=True,
                    separators=(",", ":"),
                )
            )
        elif args.command in {"prepare", "bump"}:
            identity = release_identity(args.version)
            changed = apply_projections(root, build_projections(root, identity))
            if args.command == "bump":
                print(json.dumps(_bump_receipt(identity, changed), sort_keys=True))
            else:
                print(json.dumps({"changed": [path.as_posix() for path in changed]}))
        elif args.command == "verify":
            drift = verify_projections(root)
            if drift:
                raise ReleasePreparationError(
                    "release projections drift: "
                    + ", ".join(path.as_posix() for path in drift)
                )
            print("release projections verified")
        elif args.command == "diff":
            print(
                _render_diff(
                    root, build_projections(root, release_identity(args.version))
                ),
                end="",
            )
        elif args.command == "stage":
            copied = stage_artifacts(root, args.output)
            print(json.dumps({"copied": [path.as_posix() for path in copied]}))
    except (OSError, ValueError, ReleasePreparationError) as exc:
        parser.error(str(exc))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
