"""Deterministic out-of-tree adapter package scaffolding."""

from __future__ import annotations

from dataclasses import dataclass
import json
from pathlib import Path
import re

from gigaloom.adapter_sdk import (
    AdapterConformanceClaim,
    AdapterManifest,
    adapter_manifest_to_dict,
)


@dataclass(frozen=True)
class AdapterScaffoldResult:
    """Files created for one generated adapter package."""

    root: Path
    package_name: str
    class_name: str
    files: tuple[Path, ...]


def scaffold_adapter_package(
    adapter_id: str,
    destination: str | Path,
) -> AdapterScaffoldResult:
    """Create a complete, fail-if-present adapter package scaffold."""
    root = Path(destination).resolve()
    if root.exists():
        raise FileExistsError(f"scaffold destination already exists: {root}")
    package_name = _package_name(adapter_id)
    class_name = _class_name(adapter_id)
    distribution = f"agent-workbench-{adapter_id}"
    entry_point = f"{package_name}.adapter:{class_name}Harness"
    manifest = AdapterManifest(
        adapter_id=adapter_id,
        adapter_version="0.1.0",
        distribution=distribution,
        entry_point=entry_point,
        claims=(
            AdapterConformanceClaim.EXECUTION_RUN,
            AdapterConformanceClaim.PACKAGING_ENTRY_POINT,
        ),
    )
    package_dir = root / "src" / package_name
    tests_dir = root / "tests"
    package_dir.mkdir(parents=True)
    tests_dir.mkdir()
    rendered = {
        root / "pyproject.toml": _render_pyproject(
            adapter_id=adapter_id,
            distribution=distribution,
            package_name=package_name,
            entry_point=entry_point,
        ),
        root / "README.md": _render_readme(adapter_id),
        package_dir / "__init__.py": _render_init(class_name),
        package_dir / "adapter.py": render_adapter_module(
            adapter_id,
            class_name=class_name,
        ),
        package_dir / "conformance.py": _render_conformance(package_name, class_name),
        package_dir / "adapter_manifest.json": (
            json.dumps(adapter_manifest_to_dict(manifest), indent=2, sort_keys=True)
            + "\n"
        ),
        tests_dir / "test_conformance.py": _render_test(package_name),
    }
    for path, content in rendered.items():
        path.write_text(content, encoding="utf-8")
    return AdapterScaffoldResult(
        root=root,
        package_name=package_name,
        class_name=class_name,
        files=tuple(sorted(rendered)),
    )


def render_adapter_module(adapter_id: str, *, class_name: str | None = None) -> str:
    """Render the adapter implementation template used by the CLI scaffold."""
    resolved_class_name = class_name or _class_name(adapter_id)
    AdapterManifest(
        adapter_id=adapter_id,
        adapter_version="0.1.0",
        distribution=f"agent-workbench-{adapter_id}",
        entry_point=f"{_package_name(adapter_id)}.adapter:{resolved_class_name}Harness",
    )
    return f'''"""Out-of-tree adapter implementation."""

from __future__ import annotations

from gigaloom.adapter_sdk import AdapterExecutionProtocol
from gigaloom.harnesses.base import BaseHarness
from gigaloom.types import (
    Availability,
    HarnessCapability,
    HarnessContext,
    HarnessRequest,
    HarnessResult,
    HarnessSpec,
)


class {resolved_class_name}Harness(BaseHarness):
    """Provider-neutral adapter generated by the SDK v1 scaffold."""

    def __init__(self, protocol: AdapterExecutionProtocol | None = None) -> None:
        self._protocol = protocol

    @classmethod
    def spec(cls) -> HarnessSpec:
        return HarnessSpec(
            id="{adapter_id}",
            title="{resolved_class_name}",
            kind="custom",
            description="Out-of-tree provider-neutral adapter",
            capabilities=(HarnessCapability.CHAT_COMPLETIONS,),
            icon="plug",
            supports_workspace=True,
            tags=("plugin", "sdk-v1"),
            config_schema={{
                "type": "object",
                "properties": {{}},
                "additionalProperties": False,
            }},
            metadata={{
                "sdk_api_version": 1,
                "package": "agent-workbench-{adapter_id}",
            }},
        )

    def availability(self) -> Availability:
        if self._protocol is None:
            return Availability.missing("provider protocol is not configured")
        return self._protocol.availability()

    def run(
        self,
        request: HarnessRequest,
        context: HarnessContext,
    ) -> HarnessResult:
        if self._protocol is None:
            return HarnessResult(
                ok=False,
                text="",
                error="provider protocol is not configured",
            )
        return self._protocol.run(request)
'''


def _render_pyproject(
    *,
    adapter_id: str,
    distribution: str,
    package_name: str,
    entry_point: str,
) -> str:
    return f'''[project]
name = "{distribution}"
version = "0.1.0"
description = "Out-of-tree provider-neutral Harness adapter"
requires-python = ">=3.11,<4"
dependencies = ["gigaloom>=0.5.1a1,<0.6"]

[project.entry-points."gigaloom.harness_adapters.v1"]
{adapter_id} = "{entry_point}"

[project.entry-points."gigaloom.adapter_conformance.v1"]
{adapter_id} = "{package_name}.conformance:build_conformance_subject"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/{package_name}"]
'''


def _render_readme(adapter_id: str) -> str:
    return f"""# {adapter_id}

Generated provider-neutral adapter package for SDK API v1.

The initial manifest claims only hermetic execution and package discovery.
Every other conformance category remains explicitly unsupported until its
behavior and probe are implemented.

```bash
python -m pytest -q
giga harness conformance {adapter_id} --json
```
"""


def _render_init(class_name: str) -> str:
    return f'''"""Generated provider-neutral adapter package."""

from .adapter import {class_name}Harness

__all__ = ["{class_name}Harness"]
'''


def _render_conformance(package_name: str, class_name: str) -> str:
    return f'''"""Hermetic conformance subject for the generated adapter."""

from gigaloom.adapter_sdk import (
    AdapterConformanceSubject,
    FakeProviderProtocol,
    load_packaged_adapter_manifest,
)

from .adapter import {class_name}Harness


def build_conformance_subject() -> AdapterConformanceSubject:
    protocol = FakeProviderProtocol()
    return AdapterConformanceSubject(
        manifest=load_packaged_adapter_manifest("{package_name}"),
        harness={class_name}Harness(protocol=protocol),
        fake_provider=protocol,
    )
'''


def _render_test(package_name: str) -> str:
    return f"""from gigaloom.adapter_sdk import run_adapter_conformance

from {package_name}.conformance import build_conformance_subject


def test_declared_adapter_conformance_subset():
    report = run_adapter_conformance(build_conformance_subject())

    assert report.ok is True
    assert {{result.status for result in report.results}} == {{"passed", "unsupported"}}
"""


def _package_name(adapter_id: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9_]", "_", adapter_id)
    if not normalized or not normalized[0].isalpha():
        normalized = f"adapter_{normalized}"
    return f"agent_workbench_{normalized}"


def _class_name(adapter_id: str) -> str:
    name = "".join(
        part[:1].upper() + part[1:]
        for part in re.split(r"[^A-Za-z0-9]+", adapter_id)
        if part
    )
    if not name or not name[0].isalpha():
        name = f"Adapter{name}"
    return name


__all__ = [
    "AdapterScaffoldResult",
    "render_adapter_module",
    "scaffold_adapter_package",
]
